# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-05 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_content_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id'], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AddField(
            model_name='post',
            name='is_md',
            field=models.BooleanField(default=True, verbose_name='markdown 语法'),
        ),
    ]
